module Cleric exposing (..)

import Html exposing (..)
import Message exposing (Message)
import Style exposing (..)


patch_1_121 : List (Html Message)
patch_1_121 =
    [h2 [] [text "クレリック 1.121"],
     text "クレリックはフルリスペックされる。",
     secalb "Rejuvenation (基本)",
     text "Cure Poison と Cure Disease のキャスト時間は2.4秒に短縮される。",
     secalb "Enhancements (スペック)",
     text "グループ resistance buff を pulse に変更する。3種類の resistance buff は一つにまとめられる。2000 range, 詠唱時間3.0秒, pulse は 30秒間継続3秒毎。この buff は CL buff およびパラディンの resist buff とスタックしない。",
     ulist ["Level 13 - Energy Shield - Spirit/Energy/Body resist 12%増加",
            "Level 30 - Energy Guard - Spirit/Energy/Body resist 18%増加",
            "Level 40 - Energy Barrier - Spirit/Energy/Body resist 24%増加"],
     text "Hand of God は以下のように変更される。",
     ulist ["ダメージ吸収を 85% から 50% に変更",
            "focus ではなく target は戦闘が可能",
            "5s cast, 10秒間継続, 再使用60秒, 25% power cost",
            "level 46 から 45 に変更"],
     secalb "Smite (スペック)",
     text "Minor Deliverance (PBAoE snare) をレベル 7 から 6 に変更",
     br [] [],
     text "single-target mez を追加",
     ulist ["Level 9 - Heavenly Slumber - 28秒間継続 - 3s cast - 1500 range - 5 power",
            "Level 14 - Graceful Slumber - 34秒間継続 - 3s cast - 1500 range - 8 power",
            "Level 23 - Hallowed Slumber - 40秒間継続 - 3s cast - 1500 range - 11 power",
            "Level 31 - Divine Slumber - 50秒間継続 - 3s cast - 1500 range - 15 power",
            "Level 41 - Holy Slumber - 60秒間継続 - 3s cast - 1500 range - 19 power"],
     text "single-target Instant heal を追加",
     ulist ["Level 7 - Divine Light - 再使用60秒 - Heal 15% - 2000 range - 40% power",
            "Level 28 - Holy Light - 再使用60秒 - Heal 25% - 2000 range - 40% power",
            "Level 46 - Pure Light - 再使用60秒 - Heal 45% - 2000 range - 40% power"],
     text "root 除去スペル Blessing of Movement を追加",
     ulist ["level 13, 再使用5分, 3.0 sec cast, 1500 range, 10% power.",
            "自分に対しては使用できない。"]]


patch_1_122B : List (Html Message)
patch_1_122B =
    [h2 [] [text "クレリック 1.122B"],
     secalb "Enhancements (基本)",
     text "Level 42 - Aura of Deflection - AF の値は 52 から 150 に増加する。"]


patch_1_123 : List (Html Message)
patch_1_123 =
    [h2 [] [text "クレリック 1.123"],
     text "クレリックはフルリスペックされる。",
     secalb "Rejuvenation (スペック)",
     text "単体インスタントヒール Divine Light と Pure Light はスペックに移動される。",
     secalb "Smite (基本)",
     text "スマイトは全面的に変更される。",
     br [] [],
     text "AoEスネアが追加される。",
     ulist ["Level 3 - Minor Deliverance - Instant cast - 半径350 - 29秒継続 - 再使用5分 - 9 power - 移動速度50%低下",
            "Level 13 - Lesser Deliverance - Instant cast - 半径350 - 39秒継続 - 再使用5分 - 14 power - 移動速度50%低下",
            "Level 23 - Mighty Deliverance - Instant cast - 半径350 - 47秒継続 - 再使用5分 - 21 power - 移動速度50%低下",
            "Level 33 - Greater Deliverance - Instant cast - 半径350 - 59秒継続 - 再使用5分 - 25 power - 移動速度50%低下",
            "Level 43 - Blessed Deliverance - Instant cast - 半径350 - 69秒継続 - 再使用5分 - 30 power - 移動速度50%低下"],
     text "単体スタンのレベルは次のように変更される。",
     ulist ["Level 7 - Stunning Flash",
            "Level 17 - Stunning Flare",
            "Level 27 - Stunning Glare",
            "Level 37 - Stunning Halo",
            "Level 47 - Stunning Aura"],
     text "単体DDのレベルは次のように変更される。",
     ulist ["Level 8 - Smite",
            "Level 18 - Greater Smite",
            "Level 28 - Lesser Judgement",
            "Level 38 - Greater Judgement",
            "Level 48 - Supreme Judgement"],
     secalb "Smite (スペック)",
     text "ダメージ反射自己バフが追加される。",
     ulist ["Level 10 - Virtuous Reflection - 3s cast - 20分持続 - 10% - あらゆるダメージの3%を攻撃者に反射する。",
            "Level 20 - Heavenly Reflection - 3s cast - 20分持続 - 10% - あらゆるダメージの5%を攻撃者に反射する。",
            "Level 30 - Rapturous Reflection - 3s cast - 20分持続 - 10% - あらゆるダメージの7%を攻撃者に反射する。",
            "Level 40 - Radiant Reflection - 3s cast - 20分持続 - 10% - あらゆるダメージの10%を攻撃者に反射する。"],
     text "ダメージ増加自己バフのレベルは次のように変更される。",
     ulist ["Level 1 - Hammer of Faith - 3s cast - 2 power - 物理攻撃 5 spirit damage 追加",
            "Level 11 - Hammer of Justice - 3s cast - 11 power - 物理攻撃 10 spirit damage 追加",
            "Level 21 - Hammer of Zeal - 3s cast - 15 power - 物理攻撃 14 spirit damage 追加",
            "Level 31 - Hammer of Holiness - 3s cast - 25 power - 物理攻撃 22 spirit damage 追加",
            "Level 41 - Hammer of the Sanctified - 3s cast - 33 power - 物理攻撃 35 spirit damage 追加"],
     text "単体DD呪文は次のように変更される。",
     ulist ["Level 4 - Divine Anger - 1500 range - 2.8s cast - 6 power - 32 spirit damage",
            "Level 14 - Divine Rage - 1500 range - 2.8s cast - 11 power - 60 spirit damage",
            "Level 24 - Divine Wrath - 1550 range - 2.8s cast - 19 power - 136 spirit damage",
            "Level 34 - Divine Fury - 1600 range - 2.8s cast - 25 power - 192 spirit damage",
            "Level 44 - Divine Vengeance - 1650 range - 2.8s cast - 32 power - 214 spirit damage"],
     text "単体mezz呪文のレベルは次のように変更される。",
     ulist ["Level 5 - Heavenly Slumber",
            "Level 15 - Graceful Slumber",
            "Level 25 - Hallowed Slumber",
            "Level 35 - Divine Slumber",
            "Level 45 - Holy Slumber"],
     text "単体回復バリアー呪文が追加される。単体バリアーとグループバリアーはスタックするが同種のバリアーはスタックしない。",
     ulist ["Level 6 - Barrier Heal - 1500 range - 3.0s cast - 13 power - 38回復10吸収",
            "Level 16 - Barrier Resuscitation - 1500 range - 2.9s cast - 21 power - 108回復25吸収",
            "Level 26 - Barrier Reviction - 1500 range - 2.8s cast - 32 power - 185回復40吸収",
            "Level 36 - Barrier Refection - 1500 range - 2.6s cast - 43 power - 241回復75吸収",
            "Level 46 - Barrier Refocillation - 1500 range - 2.5s cast - 55 power - 302回復100吸収"],
     text "グループ回復バリアー呪文が追加される。単体バリアーとグループバリアーはスタックするが同種のバリアーはスタックしない。",
     ulist ["Level 9 - Barrier Grace - 1500 range - 3.2s cast - 25% power - 20回復5吸収",
            "Level 19 - Barrier Commendation - 1500 range - 3s cast - 25% power - 50回復25吸収",
            "Level 29 - Barrier Benediction - 1500 range - 2.8s cast - 25% power - 145回復55吸収",
            "Level 39 - Barrier Blessing - 1500 range - 2.6s cast - 25% power - 160回復75吸収",
            "Level 49 - Barrier Absolution - 1500 range - 2.5s cast - 25% power - 205回復135吸収"],
     text "ターゲットの攻撃procデバフが追加される。ただしこのデバフよりもアイテムの攻撃proc(例えば Otherworldly Disarm)が優先される。",
     ulist ["Level 3 - Helping Hand - 1000 range - 2.8s cast - 20秒持続 - 11 power - 物理攻撃は攻撃対象を5回復する。",
            "Level 13 - Healing Hand - 1000 range - 2.8s cast - 20秒持続 - 24 power - 物理攻撃は攻撃対象を10回復する。",
            "Level 23 - Light Hand - 1000 range - 2.8s cast - 20秒持続 - 24 power - 物理攻撃は攻撃対象を25回復する。",
            "Level 33 - Pure Hand - 1000 range - 2.8s cast - 20秒持続 - 24 power - 物理攻撃は攻撃対象を60回復する。",
            "Level 43 - Holy Hand - 1000 range - 2.8s cast - 20秒持続 - 24 power - 物理攻撃は攻撃対象を100回復する。"],
     text "新しいダメージ増加バフが追加される。",
     ulist ["Level 50 - Ascendance - Instant cast - 25秒継続 - 再使用10分 - すべてのダメージが2倍になる。効果中はヒール、蘇生ができない。MoC と同時使用はできない。MoC を使うとキャンセルされる。"],
     text "単体ヒール Divine Light と Pure Light は Rejuvenation (スペック) に移動する。",
     text "ルート解除 Blessing of Movement は Smite (スペック) のままである。",
     text "PBAoE インスタントダメージ呪文のレベルが以下のように変更される。",
     ulist ["Level 8 - Drive Evil",
            "Level 18 - Repulse Evil",
            "Level 28 - Dispel Evil",
            "Level 38 - Banish Evil",
            "Level 48 - Annihilate Evil"],
     text "AoE ダメージ呪文が以下のように習性される。",
     ulist ["Level 7 - Heavenly Strike - 1500 range - 半径350 - 3s cast - 11 power - 26 spirit damage",
            "Level 17 - Heavenly Blast - 1500 range - 半径350 - 3s cast - 23 power - 52 spirit damage",
            "Level 27 - Heavenly Bolt - 1550 range - 半径350 - 3s cast - 36 power - 78 spirit damage",
            "Level 37 - Heavenly Force - 1600 range - 半径350 - 3s cast - 47 power - 102 spirit damage",
            "Level 47 - Heavenly Detonation - 1650 range - 半径350 - 3s cast - 60 power - 128 spirit damage"]]


all : List (Html Message)
all = patch_1_121 ++ patch_1_122B
      ++ patch_1_123
