module Hunter exposing (..)

import Html exposing (..)
import Message exposing (Message)
import Style exposing (..)


patch_1_121 : List (Html Message)
patch_1_121 =
    [h2 [] [text "ハンター 1.121"],
     text "ハンターはフルリスペックされる。",
     text "すべてのアーチャーは Remedy を得る。Remedy は再使用 5 分でもはや HP を失わない。毒に対する耐性を 60 秒間維持する。",
     secmid "Archery (スペック)",
     text "Critical Shot のダメージが 10% 増加する。",
     text "アーチャーの Critical Shot ペナルティーが -50% から -75% に増加する。",
     text "Standard Shot は 5 秒から 4.7 秒になる。",
     text "Elemental Shot は 7 秒から 5.5 秒になる。ダメージタイプが以下のようになる。",
     ulist ["Hunter: Benthic (cold), Tempestuous (spirit)",
            "Ranger: Pyroclasmic (heat), Entropic (energy)",
            "Scout: Lithic (matter), Somatic (body)"],
     text "Power shot は 6 秒から 4.5 秒になり、dex により修正される。",
     text "Power Shot のダメージが 13% 増加する。",
     text "Power Shot は bladeturn を貫通する。",
     text "Power shot は再使用30秒となる。",
     text "Power shot はアーチャーのダメージペナルティーの対象となる。",
     text "Rapid Fire shot は前方 90 度の cone AoE (FAE) となる。半径 700。",
     br [] [],
     text "新しく root shot が追加される。",
     ulist ["Level 18 - Bola Shot 1 - 12秒間 root - 4s cast - 2100 range",
            "Level 28 - Bola Shot 2 - 20秒間 root - 4s cast - 2100 range",
            "Level 38 - Bola Shot 3 - 28秒間 root- 4s cast - 2100 range",
            "Level 48 - Bola Shot 4 - 36秒間 root - 4s cast - 2100 range"],
     text "新しく snare shot が追加される。",
     ulist ["Level 45 - Patella Shot - 15秒間 melee hinder - 20s 再使用 - 4s cast - 2100 range"],
     text "Point Blank Shot は以下のようになる",
     ulist ["Level 16 - Point Blank Shot 1 - 74 damage - 2s cast - 90s 再使用 - 500 range - 自分を対象にした bladeturn 30 秒間, 10秒ごと",
            "Level 26 - Point Blank Shot 2 - 134 damage - 2s cast - 90s 再使用 - 500 range - 自分を対象にした bladeturn 30 秒間, 8秒ごと",
            "Level 36 - Point Blank Shot 3 - 195 damage - 2s cast - 90s 再使用 - 500 range - 自分を対象にした bladeturn 30 秒間, 6秒ごと"],
      text "Poison shot は除去される。",
      text "Acid shot は射程が 1500 に減少し 350 半径 AoE になる。",
      br [] [],
      text "Siege Shot はダメージが増加する。",
      ulist ["Siege Shot 1 - ダメージ増加 2 から 7",
             "Seige Shot 2 - ダメージ増加 7 から 21",
             "Siege Shot 3 - ダメージ増加 15 から 42",
             "Siege Shot 4 - ダメージ増加 21 から 60",
             "Siege Shot 5 - ダメージ増加 26 から 75",
             "Siege Shot 6 - ダメージ増加 37 から 90",
             "Siege Shot 7 - ダメージ増加 42 から 105",
             "Siege Shot 8 - ダメージ増加 47 から 125"],
      text "Long Shot は cast speed debuff を持つ。",
      ulist ["Long Shot 1 - 3% cast speed debuff - 40秒間継続",
             "Long Shot 2 - 6% cast speed debuff - 40秒間継続",
             "Long Shot 3 - 9% cast speed debuff - 40秒間継続",
             "Long Shot 4 - 12% cast speed debuff - 40秒間継続",
             "Long Shot 5 - 15% cast speed debuff - 40秒間継続",
             "Long Shot 6 - 18% cast speed debuff - 40秒間継続",
             "Long Shot 7 - 21% cast speed debuff - 40秒間継続",
             "Long Shot 8 - 24% cast speed debuff - 40秒間継続"],
      text "新しいスペル Track が追加される。",
      ulist ["Level 20 - 15% stealth detection bonus - 2s cast - 30秒間継続 - Focus スペルは移動または呪文の詠唱で無効化する - Self-target",
             "Level 30 - 25% stealth detection bonus - 2s cast - 30秒間継続 - Focus スペルは移動または呪文の詠唱で無効化する - Self-target",
             "Level 40 - 35% stealth detection bonus - 2s cast - 30秒間継続 - Focus スペルは移動または呪文の詠唱で無効化する - Self-target",
             "Level 50 - 45% stealth detection bonus - 2s cast - 30秒間継続 - Focus スペルは移動または呪文の詠唱で無効化する - Self-target"]]
