module Mauler exposing (..)

import Html exposing (..)
import Message exposing (Message)
import Style exposing (..)


patch_1_121 : List (Html Message)
patch_1_121 =
    [h2 [] [text "モーラー 1.121"],
     text "モーラーは変更されません。"]


patch_1_123 : List (Html Message)
patch_1_123 =
    [h2 [] [text "モーラー 1.123"],
     text "モーラーはフルリスペックされる。",
     seccommon "Staff (スペック)",
     ulist ["Level 1 - Wild Swing - Any - Medium Endurance - High Damage - Low Hit Penalty - Medium Defensive Penalty - 9秒間自分の攻撃はブレードターンを無視する。",
            "Level 2 - Splintered Strike - Follows Wild Swing - Low Endurance - Medium Damage - Low Hit Bonus - Low Defensive Bonus - ターゲットの攻撃速度を20秒間8%低下させる。",
            "Level 4 - Focused Breach - Follows Splintered Strike - Low Endurance - High Damage - Medium Hit Bonus - No Defensive Bonus - ターゲットのABSを30秒間5%低下させる。",
            "Level 8 - Percussion - Side - Medium Endurance - Low Damage - Medium Hit Bonus - Low Defensive Penalty - 5秒スタン。",
            "Level 10 - Cinder Strike - Front - Medium Endurance - Low Damage - Medium Hit Bonus - Low Defensive Bonus - 20ダメージ、与えたダメージの50%を自分のパワーとする。",
            "Level 15 - Jolting Staff - Follows Wild Swing - Medium Endurance - Medium Damage - Medium Hit Bonus - Low Defensive Bonus - 60秒間自分の物理攻撃は 50 energy damage を追加で与える。",
            "Level 21 - Turbid staff - Follows Wild Swing - Medium Endurance - Medium Damage - Medium Hit Bonus - Low Defensive Bonus - 9秒間戦闘中の移動速度を上昇させる。この効果はスピードワープを無視する。",
            "Level 25 - Wildbull's Staff - Follows Percussion - Very High Endurance - Very High Damage - No Hit Bonus - Very High Defensive Penalty - ターゲットの ablative barrier をキャンセルする。",
            "Level 29 - Ember Clip - Evade - Medium Endurance - Medium Damage - Medium Hit Bonus - Low Defensive Bonus - 20秒間ターゲットの攻撃速度を30%低下させる。",
            "Level 34 - Burning Cloud - Behind - High Endurance - High Damage - Low Hit Bonus - No Defensive Bonus - 7秒スタン",
            "Level 39 - Scorching Cloud - Follows Burning Cloud - High Endurance - Very High Damage - High Hit Bonus - Low Defensive Penalty - 30秒間ターゲットの詠唱時間を50%増加させる。",
            "Level 44 - Forging Clip - Follows Ember Clip - Medium Endurance - Very High Damage - High Hit Bonus - No Defensive Bonus - 30秒間5秒ごとに 35 heat damage を与える。",
            "Level 50 - Farseer's Staff - Follows Turbid Staff - Medium Endurance - Very High Damage - High Hit Bonus - Medium Defensive Bonus - 15秒間呪文、スタイルのパワー、endo コストがかからない。"],
     seccommon "Aura Manipulation (スペック)",
     text "ほとんどの Aura Manipulation スキルを使うためには Staff スペックを選択し Mauler Staff を装備していなければならない。",
     br [] [],
     text "以下のスペルによって Aura Manipulation スペルの効果が変化する。",
     ulist ["Aura of the Wildbull",
            "Aura of the Farseer"],
     text "Gift of Nethuni (Aura of the Wildbull) - 3s cast - 再使用45秒",
     ulist ["Level 4 - 15秒継続 - 5 power - 3秒ごとに 10 ヘルス回復",
            "Level 14 - 15秒継続 - 15 power - 3秒ごとに 25 ヘルス回復",
            "Level 24 - 15秒継続 - 35 power - 3秒ごとに 40 ヘルス回復",
            "Level 34 - 15秒継続 - 45 power - 3秒ごとに 50 ヘルス回復",
            "Level 44 - 15秒継続 - 55 power - 3秒ごとに 60 ヘルス回復"],
     text "Gift of Nethuni (Aura of the Farseer) - 3s cast - 再使用45秒",
     ulist ["Level 4 - 5 power - 25 ヘルス回復",
            "Level 14 - 15 power - 62 ヘルス回復",
            "Level 24 - 35 power - 100 ヘルス回復",
            "Level 34 - 45 power - 125 ヘルス回復",
            "Level 44 - 55 power - 150 ヘルス回復"],
     text "Gift of Tegashrig (Aura of the Wildbull) - 3s cast - 再使用15秒",
     ulist ["Level 3 - 30秒継続 - 16 power - staff weaponskill を5%増加。",
            "Level 13 - 30秒継続 - 24 power - staff weaponskill を10%増加。5 Mauler Staff 必要。",
            "Level 23 - 30秒継続 - 48 power - staff weaponskill を15%増加。15 Mauler Staff 必要。",
            "Level 33 - 30秒継続 - 60 power - staff weaponskill を20%増加。25 Mauler Staff 必要。",
            "Level 43 - 30秒継続 - 76 power - staff weaponskill を25%増加。35 Mauler Staff 必要。"],
     text "Gift of Tegashrig (Aura of the Farseer) - 3s cast - 再使用15秒",
     ulist ["Level 3 - 60秒継続 - 16 power - evasion 率を 4%増加。",
            "Level 13 - 60秒継続 - 24 power - evasion 率を 12%増加。5 Mauler Staff 必要。",
            "Level 23 - 60秒継続 - 48 power - evasion 率を 18%増加。15 Mauler Staff 必要。",
            "Level 33 - 60秒継続 - 60 power - evasion 率を 24%増加。25 Mauler Staff 必要。",
            "Level 43 - 60秒継続 - 76 power - evasion 率を 40%増加。35 Mauler Staff 必要。"],
     text "Gift of Perizor (Aura of the Wildbull) - 2.5s cast - 10% power",
     ulist ["Level 7 - 1500 range - 13秒継続 - ターゲットをルート。",
            "Level 17 - 1550 range - 26秒継続 - ターゲットをルート。5 Mauler Staff 必要。",
            "Level 27 - 1600 range - 41秒継続 - ターゲットをルート。15 Mauler Staff 必要。",
            "Level 37 - 1700 range - 61秒継続 - ターゲットをルート。25 Mauler Staff 必要。",
            "Level 47 - 1750 range - 73秒継続 - ターゲットをルート。35 Mauler Staff 必要。"],
     text "Gift of Perizor (Aura of the Farseer) - 2.5s cast - 10% power",
     ulist ["Level 7 - 1500 range - ターゲットのパワーを 12% 吸収。",
            "Level 17 - 1550 range - ターゲットのパワーを 15% 吸収。5 Mauler Staff 必要。",
            "Level 27 - 1600 range - ターゲットのパワーを 25% 吸収。15 Mauler Staff 必要。",
            "Level 37 - 1700 range - ターゲットのパワーを 30% 吸収。25 Mauler Staff 必要。",
            "Level 47 - 1750 range - ターゲットのパワーを 35% 吸収。35 Mauler Staff 必要。"],
     text "Gift of Arasthai (Aura of the Wildbull) - 5s cast - 30% power - 再使用3分",
     ulist ["Level 9 - 10秒継続 - 物理ダメージ 1%.",
            "Level 19 - 10秒継続 - 物理ダメージ 2% 増加。5 Mauler Staff 必要。",
            "Level 29 - 20秒持続 - 物理ダメージ 3% 増加。15 Mauler Staff 必要。",
            "Level 39 - 30秒継続 - 物理ダメージ 7% 増加。25 Mauler Staff 必要。",
            "Level 49 - 40秒継続 - 物理ダメージ 10% 増加。35 Mauler Staff 必要。"],
     text "Gift of Arasthai (Aura of the Farseer) - 5s cast - 30% power - 再使用3分",
     ulist ["Level 9 - 10秒継続 - 魔法ダメージ 1% 増加。",
            "Level 19 - 10秒継続 - 魔法ダメージ 2% 増加。5 Mauler Staff 必要。",
            "Level 29 - 20秒持続 - 魔法ダメージ 3% 増加。15 Mauler Staff 必要。",
            "Level 39 - 30秒継続 - 魔法ダメージ 7% 増加。25 Mauler Staff 必要。",
            "Level 49 - 40秒継続 - 魔法ダメージ 10% 増加。35 Mauler Staff 必要。"],
     text "Gift of Albion/Midgard/Hibernia (Aura of the Wildbull) - 2s cast - 1500 range - 30% power",
     ulist ["Level 5 - 45 matter/cold/heat damage",
            "Level 15 - 100 matter/cold/heat damage. 5 Mauler Staff 必要。",
            "Level 25 - 190 matter/cold/heat damage. 15 Mauler Staff 必要。",
            "Level 35 - 350 matter/cold/heat damage. 25 Mauler Staff 必要。",
            "Level 45 - 550 matter/cold/heat damage. 35 Mauler Staff 必要。"],
     text "Gift of Albion/Midgard/Hibernia (Aura of the Farseer) - 2s cast - 1500 range - 30% power",
     ulist ["Level 5 - 45 body/spirit/energy damage",
            "Level 15 - 100 body/spirit/energy damage. 5 Mauler Staff 必要。",
            "Level 25 - 190 body/spirit/energy damage. 15 Mauler Staff 必要。",
            "Level 35 - 350 body/spirit/energy damage. 25 Mauler Staff 必要。",
            "Level 45 - 550 body/spirit/energy damage. 35 Mauler Staff 必要。"],
     text "以下のスキルが追加させる。",
     ulist ["Level 50 - Aura Convergence - 5s cast - 2000 range - 半径500 - 30秒継続 - 再使用10分 - 範囲内の味方および敵からパワーを吸収する。さらに自分または味方が受けたダメージの25%は自分を回復させる。"],
     text "自己 offensive ヒール proc Gift of Renewal は変更されていない。Mauler Staff を使う必要はない。",
     text "グループニアサイト緩和パルスは削除された。",
     text "グループメツ緩和パルスは削除された。"]


all : List (Html Message)
all = patch_1_121
      ++ patch_1_123
