module Message exposing (..)


type Message =
    TopPage
  | Patch_1_121_Page
  | Patch_1_121B_Page
  | Patch_1_121C_Page
  | Patch_1_122B_Page
  | Patch_1_122B_HotFix_Page
  | Patch_1_122B_HotFix2_Page
  | Patch_1_122B_HotFix3_Page
  | Patch_1_122B_HotFix4_Page
  | Patch_1_122B_HotFix5_Page
  | AlbionPage
  | MidgardPage
  | HiberniaPage
  | AnimistPage
  | ArmsmanPage
  | BainsheePage
  | BardPage
  | BerserkerPage
  | BlademasterPage
  | BonedancerPage
  | CabalistPage
  | ChampionPage
  | ClericPage
  | DruidPage
  | EldritchPage
  | EnchanterPage
  | FriarPage
  | HealerPage
  | HereticPage
  | HeroPage
  | HunterPage
  | InfiltratorPage
  | MaulerPage
  | MentalistPage
  | MercenaryPage
  | MinstrelPage
  | NecromancerPage
  | NightshadePage
  | PaladinPage
  | RangerPage
  | ReaverPage
  | RunemasterPage
  | SavagePage
  | ScoutPage
  | ShadowbladePage
  | ShamanPage
  | SkaldPage
  | SorcererPage
  | SpiritmasterPage
  | ThanePage
  | TheurgistPage
  | ValewalkerPage
  | ValkyriePage
  | VampiirPage
  | WardenPage
  | WarlockPage
  | WarriorPage
  | WizardPage
